
#' helper function for app
#'
#' @return runs ui
#' @export ui
#' @importFrom shinyWidgets radioGroupButtons
#' @importFrom DT datatable
fluidPage(
  navbarPage(
    "FACETS Preview",
    id="navbarPage1",
    tabPanel("Load Samples",
             value="tabPanel1",
             mainPanel(
               HTML( 
                    "<div style=\"background-color: #EEEEEE; padding: 20px;font-size: 16px; \">
                    <strong>USAGE</strong> <br> Enter facets output directory for 
                     each of the samples to be reviewed. This facets output directory is of the standard format generated by 
                     cmoflow_facets. The directory should have the counts file as well as the one or many run directories 
                     (eg: facets_c50p100R0.5.6, facets_c50p300R0.5.6, etc)</div><br>"
                     ),
               wellPanel(
                 h4("Load samples from file"),
                 fileInput("fileInputTxt", label=NA),
                 actionButton("fileInputButton", "Retrieve Sample(s) from file", class = "btn-primary"),
                 HTML(
                        paste0("<br><br><strong>Note</strong>: Each line in the file is the full 
                           path to facets output directory.  Eg: 
                             <br> <p style=\"line-height: 5\"></p>
                             <div style=\"background-color: white; padding: 5px; border-width: 1px; 
                             font-family: Courier New; font-size: 12px; border-color: #CCCCCC; border-style: solid;\">
                               /ifs/res/taylorlab/.../P-0000001-T01-IM5_P-0000001-N01-IM5<br>
                               /ifs/res/taylorlab/.../P-0000002-T01-IM5_P-0000002-N01-IM5<br>etc...<br></div> ")
                      )
               ),
               h3("or",style="text-align:center"),
               wellPanel(
                 h4("Enter facets run directories"),
                 textAreaInput("samplesInputTxt", label=NA, value="/ifs/res/taylorlab/.../P-0000001-T01-IM5_P-0000001-N01-IM5\n/ifs/res/taylorlab/.../P-0000002-T01-IM5_P-0000002-N01-IM5\netc...", rows=8),
                 actionButton("sampleInputButton", "Retrieve Sample(s)", class = "btn-primary")
               ),
               width = 12
             )
    ),
    tabPanel("Samples Manifest",
             value="samplesPanel",
             mainPanel(
              DT::dataTableOutput("dtSamples"),
              width=12
             )
    ),
    tabPanel("Review Fits",
             value="reviewPanel",
             fluidRow( 
               column(4, 
                      wellPanel(
                        h4(strong("Select fit:")),
                        selectInput(inputId = "inSelect", label=NA,
                                    choices=c("Not selected")), style = "padding: 10px"
                      ),
                      wellPanel(
                        h4(strong("Select run: ")),
                        shinyWidgets::radioGroupButtons(inputId = "radioGroupButton_fitType", 
                                          choices = c("Purity", "Hisens"),
                                          selected="Hisens", 
                                          status = "primary",size = 'normal', width='100%',justified = TRUE),
                        h5(em('run parameters')),
                        verbatimTextOutput("run_params",placeholder = TRUE),
                        h5(em("alternate dipLogR")),
                        verbatimTextOutput("alt_bal_logR", placeholder = TRUE),
                        style = "padding: 10px"
                      ),
                      wellPanel(
                        h4(strong("Generate a new fit:")),
                        textInput("newDipLogR", "dipLogR "),
                        textInput("newCval", "cval "),
                        
                        actionButton("buttonRefit", "Run", class = "btn-primary", width = '100%'),
                        tags$small(paste0(
                          "Note: Click 'Run' to submit re-fit job onto luna.  Takes upto a min for the job to finish."
                        )),
                        style = "padding: 10px"
                      )
               ),
               column(8,
                      tags$head(tags$style(
                        type="text/css",
                        "#image img {max-width: 80%; width: 80%; height: 80%}"
                      )),
                      imageOutput("pngImage1")
               )
             )
      )
    )
)

