
#' helper function for app
#'
#' @return runs ui
#' @export ui
#' @importFrom shinyWidgets radioGroupButtons
#' @importFrom DT datatable
#' @import shinyjs 
ui <- 
  fluidPage(
   shinyjs::useShinyjs(),
    navbarPage(
      "FACETS Preview",
      id="navbarPage1",
      tabPanel("Load Samples",
               value="tabPanel_sampleInput",
               mainPanel(
                 shinyjs::hidden(
                   wellPanel(id = "wellPanel_mountFail", 
                             style = "background-color: white; border-color: white; ",
                             HTML(
                               paste0("<div style=\"font-size: 16px; font-family: georgia; color: red; display: inline-block\">
                                      <i class=\"fa fa-exclamation-triangle\" aria-hidden=\"true\"></i><strong> /ifs/ not mounted. Nothing is gonna work!  </strong></div>")
                             ),
                             actionButton("button_mountFailRefresh", "Check for mount again", icon = icon("refresh"))
                             
                   )
                 ),
                 HTML( 
                   "<div style=\"background-color: #EEEEEE; padding: 20px;font-size: 16px; \">
                   <strong>USAGE</strong> <br> Enter facets output directory for 
                   each of the samples to be reviewed. This facets output directory is of the standard format generated by 
                   cmoflow_facets. The directory should have the counts file as well as the one or many run directories 
                   (eg: facets_c50p100R0.5.6, facets_c50p300R0.5.6, etc)</div><br>"
                 ),
                 wellPanel(
                   h4("Load samples from file"),
                   fileInput("fileInput_filename", label=NA),
                   actionButton("button_fileInput", "Retrieve Sample(s) from file", class = "btn-primary")
                   #                 HTML(
                   #                        paste0("<br><br><strong>Note</strong>: Each line in the file is the full 
                   #                           path to facets output directory.  Eg: 
                   #                             <br> <p style=\"line-height: 5\"></p>
                   #                             <div style=\"background-color: white; padding: 5px; border-width: 1px; 
                   #                             font-family: Courier New; font-size: 12px; border-color: #CCCCCC; border-style: solid;\">
                   #                               /ifs/res/taylorlab/.../P-0000001-T01-IM5_P-0000001-N01-IM5<br>
                   #                               /ifs/res/taylorlab/.../P-0000002-T01-IM5_P-0000002-N01-IM5<br>etc...<br></div> ")
                   #                      )
                 ),
                 h3("or",style="text-align:center"),
                 wellPanel(
                   h4("Enter facets run directories"),
                   textAreaInput("textAreaInput_samplesInput", label=NA, value="/ifs/res/taylorlab/.../P-0000001-T01-IM5_P-0000001-N01-IM5\n/ifs/res/taylorlab/.../P-0000002-T01-IM5_P-0000002-N01-IM5\netc...", rows=8),
                   actionButton("button_samplesInput", "Retrieve Sample(s)", class = "btn-primary")
                 ),
                 width = 12
                 )
      ),
      tabPanel("Samples Manifest",
               value="tabPanel_samplesManifest",
               mainPanel(
                 DT::dataTableOutput("datatable_samples"),
                 width=12
               )
      ),
      tabPanel("Review Fits",
               value="tabPanel_reviewFits",
               fluidRow( 
                 column(4, 
                        wellPanel(
                          h4(strong("Select fit:")),
                          selectInput(inputId = "selectInput_selectFit", label=NA,
                                      choices=c("Not selected")), style = "padding: 10px"
                        ),
                        wellPanel(
                          h4(strong("Select run: ")),
                          shinyWidgets::radioGroupButtons(inputId = "radioGroupButton_fitType", 
                                                          choices = c("Purity", "Hisens"),
                                                          selected="Hisens", 
                                                          status = "primary",size = 'normal', width='100%',justified = TRUE),
                          actionButton("button_copyClipPath", "Copy path to clipboard", 
                                       icon = icon("clipboard"), 
                                       style="height:28px;font-size:8pt;vertical-align: middle; color:darkblue"),
                          h5(em('run parameters')),
                          verbatimTextOutput("verbatimTextOutput_runParams",placeholder = TRUE),
                          h5(em("alternate dipLogR")),
                          verbatimTextOutput("verbatimTextOutput_altBalLogR", placeholder = TRUE),
                          style = "padding: 10px"
                        ),
                        wellPanel(
                          h4(strong("Generate a new fit:")),
                          shinyjs::hidden(div(id="div_watcherSuccess", HTML(" Watcher status: <i class=\"fa fa-check\" aria-hidden=\"true\"></i>"), style="color: green")),
                          shinyjs::hidden(div(id="div_watcherFail", HTML(" Watcher status: <i class=\"fa fa-times\" aria-hidden=\"true\"></i>"), style="color: red")),
                          textInput("textInput_newDipLogR", "dipLogR "),
                          textInput("textInput_newCval", "cval "),
                          
                          actionButton("button_refit", "Run", class = "btn-primary", width = '100%'),
                          tags$small(paste0(
                            "Note: Click 'Run' to submit re-fit job onto luna.  Takes upto a min for the job to finish."
                          )),
                          style = "padding: 10px"
                        )
                 ),
                 column(8,
                        mainPanel(
                          tabsetPanel(
                            tabPanel("PNG image", imageOutput("imageOutput_pngImage1")),
                            tabPanel("Segments", mainPanel(DT::dataTableOutput("datatable_cncf"), width=12))
                          )
                        )
                       #tags$head(tags$style(
                       #  type="text/css",
                       #  "#image img {max-width: 80%; width: 80%; height: 80%}"
                       #)),
               )
      )
    )
  )
)
